### ISSUE TITLE
最近好像要改版了，想問作者能否更新成新版本不然舊版之後就不能用了

### ISSUE THREAD

**Issue by LucasTsaiTw** [umts111321/TronClass-PDF-Downloader#3]
<img width="655" alt="截圖 2022-09-26 上午5 58 31" src="https://user-images.githubusercontent.com/81616595/192167497-94a34cbb-947a-4099-9c21-a891afe4a815.png">

網址
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#action-api-unification

**Comment by fish-can** [comment]
感謝您的通知，
我會盡快進行改版。

**Comment by fish-can** [comment]
@Lucas-Tsai-source 已遷移到 Manifest V3
網址: https://github.com/fish-can/TronClass-PDF-Downloader/releases/tag/v2.0
